### ISSUE TITLE
Python 3.8 Literal shape

### ISSUE THREAD

**Issue by jgbos** [rsokl/phantom-tensors#40]
Ran into this issue using Python 3.8, not sure there is a solution though:

```python
from phantom_tensors import parse
from phantom_tensors.numpy import NDArray
from typing import Literal, NewType
import numpy as np
X = NewType("X", int)
x = np.zeros((1, 2))
parse((x, NDArray[Literal[1], X]))
TypeError: Got shape-type (typing.Literal[1], <function NewType.<locals>.new_type at 0x7f60a5aab430>) with dim typing.Literal[1]. Valid dimensions are `type[int] | Unpack | TypeVar | NewType | Literal`
```

**Comment by rsokl** [comment]
Hmm.. This seems to run just fine in Python 3.9. Probably a fiddly runtime detail for literals in earlier versions of Python. It is surprising, though, because I run CI vs older version of Python. Can you try using `typing_extensions.Literal` instead?

It looks like there are some CI failures that I need to get to for this project. Maybe I will unearth what is going on here when I do.

**Comment by jgbos** [comment]
Ah yes, forgot I could try `typing_extensions`.  That solved this issue.
